### DISCUSSION TITLE
Excluding files and folders from a result container

### DISCUSSION THREAD

**Discussion by xSAVIKx** [GoogleCloudPlatform/buildpacks#301] [Q&A] [answered]
Hey! I've been using `builder` and `run` images and have a task of building a Cloud Functions and Cloud Run compatible containers.

So I decided to go with buildpacks and have a Python Functions Framework app. Now, while this is a real world and not some example, I do have tons of different folders/files in the repo that I don't want to be included. E.g. the `.git` and `.venv` or the `tests` folder.

I was going over the buildpacks [docs](https://buildpacks.io/docs/reference/config/project-descriptor/#iobuildpacks-_table-optional_) and looks like I should be using the `exclude` (or `include`) configs in my `project.toml`, but I struggle to make it work.

Here's an example `project.toml` I'm trying to use:
```toml
[project]
id = "com.example.id"
name = "App Name"
authors = ["some authors"]
version = "1.2.3"

[io.buildpacks]
builder = "gcr.io/buildpacks/google-22/builder:latest"
include = [
    "dist/",
    "app_package/",
    "main.py",
    "project.toml",
    "pyproject.toml",
    "poetry.lock",
    "requirements.txt",
    "poetry.toml"
]

[[build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "handle"

[[build.env]]
name = "GOOGLE_FUNCTION_SIGNATURE_TYPE"
value = "http"

[[build.env]]
name = "GOOGLE_FUNCTION_SOURCE"
value = "main.py"

[[build.env]]
name = "GOOGLE_RUNTIME"
value = "python"

[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "3.11.3"
```
and here's how the file tree looks like:
```text
├── .git/
├── .mypy_cache/
├── .pytest_cache/ 
├── app_package/
├── call-service.http
├── deploy-personal-service.sh
├── dist/
├── main.py
├── mypy.ini
├── poetry.lock
├── poetry.toml
├── __pycache__
├── pyproject.toml
├── README.md
├── _reports
├── requirements.txt
├── tests/
└── update-container.sh
```

And then I run my pack as:
```shell
pack build gcr.io/<project>/app-name --descriptor project.toml --builder gcr.io/buildpacks/google-22/builder:latest --run-image gcr.io/buildpacks/google-22/run:latest --clear-cache --tag gcr.io/<project>/app-name:latest --tag gcr.io/<project>/app-name:<hash> --tag gcr.io/<project>/app-name:v1.2.3 --publish
```
