### DISCUSSION TITLE
Env vars are missing in the built image

### DISCUSSION THREAD

**Discussion by tdclaritum** [GoogleCloudPlatform/buildpacks#349] [Q&A]
I have tried to build an image for our app that should be deployed on App Engine. The following command is used to build the image:

```
pack -v build --builder gcr.io/gae-runtimes/buildpacks/google-gae-22/php/builder  --run-image lca-runner eu.gcr.io/XXX/appengine/default.20231003161300:latest --clear-cache --env GAE_APPLICATION_YAML_PATH="app.yaml"
```

The custom run image is because the default one is missing `libzip4` (but I don't believe this is important).

The `app.yaml` file contains the following:

```
env_variables:
    # populate these to use the "mysql" or "postres" backends
    DB_SOCKET: "/cloudsql/III:XXX:DDD"
    DB_USER: "user"
    DB_PASS: "pass"
    DB_NAME: "db"
```

The final image is build without any issues but the env vars are not set. Because of this the image is unusable when deployed on App Engine, because it can't connect to the DB.

The question is what I'm doing wrong and what to change, so the env vars are set properly?
