### ISSUE TITLE
Cloud Build fails for python Google Function (functions-framework)

### ISSUE THREAD

**Issue by jameslittle** [GoogleCloudPlatform/buildpacks#140]
When using `GOOGLE_FUNCTION_TARGET`, the build works okay locally. Example below:
`pack --verbose build <FUNC_NAME> --clear-cache --builder gcr.io/buildpacks/builder:v1 --env GOOGLE_FUNCTION_TARGET=<FUNC_NAME>`

But when I trigger this in Cloud Build in GCP, it fails (with a permissions error) when trying to precompile the python code. Snippet below; full build log is attached. Kind of looks like it's failing when trying to create __pycache__ directories, but since I can't reproduce locally, it's difficult to troubleshoot. Relevant code seems to be in cmd/python/functions_framework/main.go

Builds for regular python web apps (Flask/gunicorn) don't seem to do this compile step.

```
=== Python - Functions Framework (google.python.functions-framework@0.9.5) ===
--------------------------------------------------------------------------------
Running "python3 -m compileall -f -q ."
*** Error compiling './cloud_apps/costpricer_web_api.py'...
PermissionError: [Errno 13] Permission denied: './cloud_apps/__pycache__'
*** Error compiling './cloud_apps/functions.py'...
PermissionError: [Errno 13] Permission denied: './cloud_apps/__pycache__'
Done "python3 -m compileall -f -q ." (110.672077ms)
```

[build.log](https://github.com/GoogleCloudPlatform/buildpacks/files/6717287/build.log)

**Comment by di** [comment]
A few things to try:
* Can you check the permissions on these directories locally? `ls -ld cloud_apps` and `ls -ld cloud_apps/__pycache__`
* Can you try removing the `__pycache__` directory locally before submitting the build? 

Could you also give us some more details about how you're submitting the build? What platform you're on, etc. Are you invoking `gcloud builds submit` locally, pushing this to a source repository, etc?

**Comment by jameslittle** [comment]
Hi @di 

The build is automatically triggered on push to git branch (code is in Cloud Source Repos). The `__pycache__` dirs definitely don't exist in the repo; have double checked this.

**Comment by di** [comment]
But `cloud_apps` does? What are the permissions on that directory?

**Comment by jameslittle** [comment]
AFAIK there's no way of setting permissions on a directory in a git repo. Git tracks the executable-bit on _files_ only. 
The command below just ends up showing the perms on the files under that dir, and they're 644.

I would imagine on Linux, the directories end up inheriting permissions from the system's (or user's) umask.

```
λ git ls-files -s cloud_apps
100644 7341dbad696158535a179ca99b4e97268a654100 0       cloud_apps/costpricer_web_api.py
100644 86a2327b3f8f3f32af19e1441b88220cc2cfdbad 0       cloud_apps/functions.py
```

**Comment by di** [comment]
I tried to reproduce this with the following and couldn't ([output here](https://gist.github.com/di/3c998efc64dece41c0e570b41561845b)):

```
$ tree
.
├── cloud_apps
│   ├── costpricer_web_api.py
│   └── functions.py
├── cloudbuild.yaml
└── main.py

1 directory, 4 files
```
```
$ cat cloudbuild.yaml
steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args: ["pack", "--verbose", "build", "hello", "--clear-cache", "--builder", "gcr.io/buildpacks/builder:v1", "--env", "GOOGLE_FUNCTION_TARGET=hello"]
 ```
 ```
$ cat main.py
 from cloud_apps import *


def hello(request):
    return "hi"
 ```

Is there anything different about how you're invoking `pack` here? Are you able to produce a minimally reproducing example so we can debug?

**Comment by jameslittle** [comment]
I think to reproduce you'd have to setup a build that is triggered remotely in GCP by git branch pushes, or tag creations. 
This is part of the workflow if you setup a Cloud Run instance with Continuous Deployment (which is what I've done).

I've attached another build log where you can see it doing the git fetch at the top. I suspect there's a change of user, between doing the fetch and running the pack build. As a workaround I've stopped using `GOOGLE_FUNCTION_TARGET` and instead I set  `GOOGLE_ENTRYPOINT ` to `functions-framework --target <function_name>` , and I guess that bypasses the problematic step.

[log-47925515-3692-42f9-bd22-0bcfd2bb1cf3.txt](https://github.com/GoogleCloudPlatform/buildpacks/files/6719853/log-47925515-3692-42f9-bd22-0bcfd2bb1cf3.txt)

**Comment by di** [comment]
Ok, so it looks like you followed https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build#new-service then, is that right?

I followed this guide, using Cloud Source Repositories for the provider and Cloud Buildpacks for the build type. It created the following Cloud Build configuration:

```yaml
steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: gcb-trigger-id=b6debbf6-c677-4a8e-acb1-c5f1cd6991e6
  _TRIGGER_ID: b6debbf6-c677-4a8e-acb1-c5f1cd6991e6
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: test-buildpacks
  _DEPLOY_REGION: us-central1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - test-buildpacks
```

And then I added this:

```diff
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
+      - '--env'
+      - GOOGLE_FUNCTION_TARGET=hello
    id: Buildpack
    entrypoint: pack
```

And the build succeeded with the above example.

Can you provide us with the inline build configuration you're using? You can find this by going to https://console.cloud.google.com/run -> your service name -> "Edit continuous deployment" -> "Configuration" -> "Open editor"
