### ISSUE TITLE
Document usage in Cloud Build and Tekton

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/buildpacks#17]
Filing an issue here to get feedback before I write up a PR to add the docs.

- Would this be an appropriate place to document how to use these buildpacks (and buildpacks in general) in Cloud Build and Tekton?
- If so, would you prefer that in README.md, or in some other docs directory, etc.?

**Comment by jamesward** [comment]
Ditto Cloud Build.

**Comment by lukasberger** [comment]
README.md sounds good for now. We have a link to tekton [1] under the Usage section, but are missing a Cloud Build link. It'd be nice to have sample commands to run as well, although I do worry about them getting out of sync.

[1] https://github.com/tektoncd/catalog/tree/master/buildpacks

**Comment by jamesward** [comment]
Oh wow. I missed the part where @ImJasonH said "in Cloud Build" :)  Was thinking about Matt's tweet about just Tekton while reading this.  Anywhoo.  Here is a sample Cloud Build step:
```
steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder', '--path', 'sample-go', '--publish', 'gcr.io/$PROJECT_ID/sample-go:$COMMIT_SHA']
```
