### ISSUE TITLE
Latest version of buildpack doesn't work in skaffold v1.17.2

### ISSUE THREAD

**Issue by agulowaty** [GoogleCloudPlatform/buildpacks#196]
It appears that some change pushed to `gcr.io/buildpacks/builder` after `6a2272a3600b93a6db0124ca98b725609099e30f` build breaks compatibility with older versions of skaffold.

Skaffold version: v1.17.2

Given skaffold directive:

```
    - image: gcr.io/***********
      context: storage
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        env:
          - "GOOGLE_RUNTIME=nodejs"
```

```
$ skaffold dev
Building [gcr.io/***********]...
v1: Pulling from buildpacks/builder
Digest: sha256:a5eef9b51163b8c4dcf52ed9f0a3372003acff09268f63cd34b1f40026d57628
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:c35bc7bff1a36de095b6ab1e215ea74aba078bb7aae7df3eb2b870f4a3259276
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
exiting dev mode because first build failed: validating stack mixins: buildpack google.go.runtime@0.9.1 does not support stack google
```

Please have a look into this issue. 

As a workaround, it worked for version 1.37.1 of skaffold. We had to downgrade the builder image to older tag.
