### ISSUE TITLE
skaffold doesn't build arm64 image

### ISSUE THREAD

**Issue by jbrinnand** [GoogleCloudPlatform/buildpacks#286]
I am building on a Macbook pro with an Intel chip architecture. I am trying to build and deploy a container on a remote arm64 cluster. It looks like skaffold detects the target platform but says it doesn't support it. "WARN[0000] builder for artifact "<my-repo>" doesn't support building for target platforms: "linux/arm64". Building for supported platforms "linux/amd64" instead.  subtask=<my-repo> task=Build
Cleaning up...

Here is my skaffold.yml.

`apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: spring-boot-jib
build:
  artifacts:
    - image: <my-repo>
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - kubernetes/springboot-jib-deploy.yaml
    - kubernetes/springboot-jib-ingress.yaml
deploy:
  kubectl: {}`
  
Also - I am trying to build an image using Java 19. If this is not supported currently, can the build be configured to use it. I can build the image using Maven and deploy it locally.  The problem is skaffold. It won't build arm64 images. 

Any help would be appreciated.

**Comment by jbrinnand** [comment]
Jib will make arm64 images. Note: the envTemplate requires that the VERSION be defined in the environment: 

export VERSION=0.0.1

```
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: spring-boot-jib

build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: <your-repo>/<your-id>/springboot-jib-skaffold-arm64
      jib:
        type: maven
        fromImage: registry-1.docker.io/sapmachine:19.0.2@sha256:899093ed8b230b827dd2eac415ef84b9d0af3d42142b7f3b4906375906cba676

manifests:
  rawYaml:
    - kubernetes/springboot-jib-deploy.yaml
    - kubernetes/springboot-jib-ingress.yaml

deploy:
  kubectl: {}
  
```
The fromImage uses sapmachines Java19 arm64 image as a base. The build command is:

skaffold build

That should do it.
