### ISSUE TITLE
Buildpacks build fails in Cloud Build due to recent changes

### ISSUE THREAD

**Issue by m11o** [GoogleCloudPlatform/buildpacks#487]
**Describe the bug**

When using Cloud Build to build a project with Buildpacks, an error occurs during the build process.

**Additional context**
How are you using GCP buildpacks?
- [x] `pack` and the `gcr.io/buildpacks/builder`
- [ ] Cloud Functions
- [ ] Cloud Run
- [x] Cloud Build
- [ ] App Engine Standard
- [ ] App Engine Flex
- [ ] Firebase App Hosting

**Did this used to work?**
*Yes*
Was this working before? When did you start noticing these errors?

**What language is your project primarily written in?**
*Go*

**Steps To Reproduce**

Bellow configures in cloudbuild.yml

```
steps:
  - name: docker.io/buildpacksio/pack
    env:
      - GOOGLE_BUILDABLE=github.com/xxx/yyy/backend/cmd/server
    args:
      - build
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/yyyy:$COMMIT_SHA
      - --builder
      - gcr.io/buildpacks/builder:v1
      - --network
      - cloudbuild
      - --buildpack
      - from=builder
      - --buildpack
      - datadog/serverless-buildpack:latest
      - --path
      - backend
      - --env
      - GOOGLE_BUILDABLE
      - --verbose
    id: Buildpack
    entrypoint: pack
```

**Expected behavior**
The build process should complete successfully and produce a working application image.

**Actual behavior**
What actually happened?

The build process fails with the following error:

```
Running "go build -o /layers/google.go.build/bin/main github.com/xxx/yyy/cmd/server (GOCACHE=/layers/google.go.build/gocache)"
Done "go build -o /layers/google.go.build/bin/main github.com/heyi..." (1m52.018711372s)
=== Utils - Label Image (google.utils.label-image@0.0.2) ===
=== In Datadog Buildpack ===
=== Copying datadog-init ===
=== Detecting command and args ===
all files = [/layers/google.go.build/launch.toml]
[[processes]]
  type = "web"
  command = ["/layers/google.go.build/bin/main"]
  default = true
panic: could not find the command
goroutine 1 [running]:
main.main()
	/Users/maxime.david/dd/crun/buildpack/detect-launch/main.go:98 +0x205
Timer: Builder ran for 3m56.22082942s and ended at 2025-02-19T00:46:10Z
ERROR: failed to build: exit status 2
ERROR: failed to build: executing lifecycle: failed with status code: 51
Finished Step #0 - "Buildpack"
ERROR
ERROR: build step 0 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1
```

If applicable, add screenshots / logs / error messages

**Further Investigation**
Based on our investigation, the build results differ between the following two commits:

361f23d349458eb052a3d6b43f6cf41a5f503037: The build succeeds with this commit.

f8f164dae7621c35acad655090204b9cc2d2f906: The build fails with this commit.

The differences between these commits can be found here:
[Compare changes](https://github.com/GoogleCloudPlatform/buildpacks/compare/361f23d349458eb052a3d6b43f6cf41a5f503037...f8f164dae7621c35acad655090204b9cc2d2f906)
