### ISSUE TITLE
Failure: (ID: 194879d1) Failed to run /bin/build: for Python, an entrypoint must be manually set..

### ISSUE THREAD

**Issue by Claus1** [GoogleCloudPlatform/buildpacks#92]
My app.yaml for python app:
```
runtime: python
env: flex
entrypoint: python guiserver.py
runtime_config:
  python_version: 3.6

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10
network:
  session_affinity: true
```
I got: 
```=== Python - pip (google.python.missing-entrypoint@0.9.0) ===
Step #0 - "Buildpack": Failure: (ID: 194879d1) Failed to run /bin/build: for Python, an entrypoint must be manually set, either with "GOOGLE_ENTRYPOINT" env var or by creating a "Procfile" file.
```

I use asyncio directly, maybe I have to use flask, gunicorn for running my app?
